services:
  mlflow:
    build: mlflow
    ports:
      - 5001:5001
    volumes:
      - ./mlflow/data:/mldata
  webapp:
    build: web_app
    ports:
      - 8501:8501
    develop:  
      watch:
        - action: rebuild
          path: ./web_app
          target: app.py